# Build the Docker image using the 'gcr.io/cloud-builders/docker' image.
# The image tag is 'us-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image'.
# The build context is '.' (the current directory).
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image', '.']

# Push the built image to Artifact Registry using the 'gcr.io/cloud-builders/docker' image.
# The image tag is 'us-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image'.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image']

# Deploy the image to Cloud Run using the 'gcr.io/cloudrun/deploy' image.
# The service name is 'my-cloud-run-service'.
# The image tag is 'us-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image'.
  - name: 'gcr.io/cloudrun/deploy'
    args: ['--image', 'us-west1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image', '--region', 'us-west1', '--platform', 'managed', '--service', 'my-cloud-run-service']

# Configure Cloud Build to store build logs in Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY
